# Generated by Django 6.0.4 on 2026-04-17 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0002_property_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='created_at',
        ),
    ]
